"""Add seed data for testing

Revision ID: a1b2c3d4e5f6
Revises: ce868ca4b38b
Create Date: 2026-01-20 17:02:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
import uuid


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'ce868ca4b38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Insert sample users
    op.execute("""
        INSERT INTO users (email, password_hash, is_internal, created_at) VALUES
        ('admin@example.com', 'pbkdf2:sha256:260000$salt$hash', true, '2026-01-20 16:00:00'),
        ('user1@example.com', 'pbkdf2:sha256:260000$salt$hash', false, '2026-01-20 16:30:00'),
        ('user2@example.com', 'pbkdf2:sha256:260000$salt$hash', false, '2026-01-20 17:00:00'),
        ('business@example.com', 'pbkdf2:sha256:260000$salt$hash', false, '2026-01-20 17:30:00');
    """)

    # Insert sample operations
    op.execute("""
        INSERT INTO operations (operation_id, type, amount, carbon_score, user_email, created_at) VALUES
        ('550e8400-e29b-41d4-a716-446655440001', 'transport', 150.50, 25.75, 'user1@example.com', '2026-01-20 16:45:00'),
        ('550e8400-e29b-41d4-a716-446655440002', 'energy', 200.00, 45.20, 'user1@example.com', '2026-01-20 16:50:00'),
        ('550e8400-e29b-41d4-a716-446655440003', 'food', 75.25, 12.50, 'user2@example.com', '2026-01-20 17:15:00'),
        ('550e8400-e29b-41d4-a716-446655440004', 'transport', 300.00, 52.30, 'business@example.com', '2026-01-20 17:45:00'),
        ('550e8400-e29b-41d4-a716-446655440005', 'energy', 500.75, 95.60, 'business@example.com', '2026-01-20 18:00:00'),
        ('550e8400-e29b-41d4-a716-446655440006', 'food', 125.00, 22.80, 'user1@example.com', '2026-01-20 18:15:00'),
        ('550e8400-e29b-41d4-a716-446655440007', 'transport', 85.00, 15.40, 'user2@example.com', '2026-01-20 18:30:00'),
        ('550e8400-e29b-41d4-a716-446655440008', 'energy', 175.50, 38.90, 'user2@example.com', '2026-01-20 18:45:00'),
        ('550e8400-e29b-41d4-a716-446655440009', 'food', 95.75, 18.20, 'business@example.com', '2026-01-20 19:00:00'),
        ('550e8400-e29b-41d4-a716-446655440010', 'transport', 220.00, 41.10, 'user1@example.com', '2026-01-20 19:15:00');
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Delete sample operations
    op.execute("""
        DELETE FROM operations WHERE operation_id IN (
            '550e8400-e29b-41d4-a716-446655440001',
            '550e8400-e29b-41d4-a716-446655440002',
            '550e8400-e29b-41d4-a716-446655440003',
            '550e8400-e29b-41d4-a716-446655440004',
            '550e8400-e29b-41d4-a716-446655440005',
            '550e8400-e29b-41d4-a716-446655440006',
            '550e8400-e29b-41d4-a716-446655440007',
            '550e8400-e29b-41d4-a716-446655440008',
            '550e8400-e29b-41d4-a716-446655440009',
            '550e8400-e29b-41d4-a716-446655440010'
        );
    """)

    # Delete sample users
    op.execute("""
        DELETE FROM users WHERE email IN (
            'admin@example.com',
            'user1@example.com',
            'user2@example.com',
            'business@example.com'
        );
    """)

    # ### end Alembic commands ###
